spring:
  application:
    name: backend-repo
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres?user=${DB_USERNAME}&password=${DB_PASSWORD}&prepareThreshold=0
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: 0
      ssl:
        enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_APP_EMAIL}
    password: ${GOOGLE_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloudinary:
  cloud_name: ${CLOUDINARY_NAME}
  api_key: ${CLOUDINARY_KEY}
  api_secret: ${CLOUDINARY_SECRET}

rsa:
  private-key: certs/private-key.pem
  public-key: certs/public-key.pem

midtrans:
  server:
    key: ${MIDTRANS_SERVER_KEY}
  client:
    key: ${MIDTRANS_CLIENT_KEY}
  is:
    production: false
